// Mock data for demo/development when TMDB API key is not configured
// All image paths use real TMDB poster/backdrop paths for authentic look

export const MOCK_MOVIES = [
  {
    id: 550988,
    title: "Deadpool & Wolverine",
    original_title: "Deadpool & Wolverine",
    overview: "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeland comes under threat, Wade must reluctantly suit-up again with an even more reluctantlier... reluctanter? Reluctantest? Wade must suit-up with Wolverine.",
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    release_date: "2024-07-24",
    vote_average: 7.7,
    vote_count: 8234,
    genre_ids: [28, 35, 878],
    popularity: 9823,
  },
  {
    id: 653346,
    title: "Kingdom of the Planet of the Apes",
    original_title: "Kingdom of the Planet of the Apes",
    overview: "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows.",
    poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    backdrop_path: "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
    release_date: "2024-05-08",
    vote_average: 7.0,
    vote_count: 3912,
    genre_ids: [878, 12, 28],
    popularity: 4231,
  },
  {
    id: 1022789,
    title: "Inside Out 2",
    original_title: "Inside Out 2",
    overview: "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust don't quite know how to feel when Anxiety shows up unannounced.",
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdrop_path: "/xg27NrXi7VXCGUr7MlcbgrMR2Ac.jpg",
    release_date: "2024-06-11",
    vote_average: 7.7,
    vote_count: 5421,
    genre_ids: [16, 10751, 18],
    popularity: 5892,
  },
  {
    id: 748783,
    title: "The Garfield Movie",
    original_title: "The Garfield Movie",
    overview: "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
    poster_path: "/xYes66HLCqniVFGbBqmfDFq3eGd.jpg",
    backdrop_path: "/ig5wOiWFJP6p9M9Uqpua0DGOXDB.jpg",
    release_date: "2024-05-24",
    vote_average: 7.0,
    vote_count: 2934,
    genre_ids: [16, 35, 10751],
    popularity: 3201,
  },
  {
    id: 519182,
    title: "Despicable Me 4",
    original_title: "Despicable Me 4",
    overview: "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, and the family is forced to go on the run.",
    poster_path: "/wWba3TaojhK7NdycyUDUkFsv0lm.jpg",
    backdrop_path: "/lgkgd8pact0FN7LPmg79BKBQ0Eu.jpg",
    release_date: "2024-07-03",
    vote_average: 7.2,
    vote_count: 1843,
    genre_ids: [16, 35, 10751, 28],
    popularity: 6543,
  },
  {
    id: 573435,
    title: "Bad Boys: Ride or Die",
    original_title: "Bad Boys: Ride or Die",
    overview: "After their late chief is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
    poster_path: "/oGythE98MYleE6mZlGs5oBGkux1.jpg",
    backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
    release_date: "2024-06-07",
    vote_average: 7.0,
    vote_count: 3156,
    genre_ids: [28, 35, 80],
    popularity: 4762,
  },
  {
    id: 1011985,
    title: "Kung Fu Panda 4",
    original_title: "Kung Fu Panda 4",
    overview: "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will meet a cunning villain, who plans to use a magical staff to resurrect all the evil villains that Po has vanquished to the spirit realm.",
    poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    release_date: "2024-03-08",
    vote_average: 7.2,
    vote_count: 2943,
    genre_ids: [16, 28, 12, 35],
    popularity: 3892,
  },
  {
    id: 823464,
    title: "Godzilla x Kong: The New Empire",
    original_title: "Godzilla x Kong: The New Empire",
    overview: "Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins and connection to Skull Island's mysteries.",
    poster_path: "/tMefBSflR6PGQLv7WvFPpgjD9uf.jpg",
    backdrop_path: "/xRd1eJIDe7JHO5KFG7cOJegaIQj.jpg",
    release_date: "2024-03-29",
    vote_average: 7.0,
    vote_count: 4125,
    genre_ids: [28, 878, 12],
    popularity: 5234,
  },
  {
    id: 786892,
    title: "Furiosa: A Mad Max Saga",
    original_title: "Furiosa: A Mad Max Saga",
    overview: "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by the Immortan Joe.",
    poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    backdrop_path: "/lOCDifNXCGZu7tiJFtFCBFoYZgO.jpg",
    release_date: "2024-05-22",
    vote_average: 7.7,
    vote_count: 3241,
    genre_ids: [28, 12, 878],
    popularity: 4103,
  },
  {
    id: 944543,
    title: "The Fall Guy",
    original_title: "The Fall Guy",
    overview: "Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while the fate of an entire production hangs in the balance.",
    poster_path: "/tSz1qsmSJon0rqjHBxXZmrotuse.jpg",
    backdrop_path: "/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg",
    release_date: "2024-05-01",
    vote_average: 7.3,
    vote_count: 2134,
    genre_ids: [28, 35, 10749],
    popularity: 3567,
  },
];

export const MOCK_PEOPLE = [
  { id: 525, name: "Christopher Nolan", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20movie%20director%20Christopher%20Nolan?width=200&height=300&nologo=true", known_for_department: "Directing" },
  { id: 6193, name: "Leonardo DiCaprio", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Leonardo%20DiCaprio?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 1245, name: "Scarlett Johansson", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actress%20Scarlett%20Johansson?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 1136406, name: "Tom Holland", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Tom%20Holland?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 74568, name: "Chris Pratt", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Chris%20Pratt?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 16828, name: "Margot Robbie", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actress%20Margot%20Robbie?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 3131, name: "Zendaya", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actress%20Zendaya?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 17419, name: "Ryan Reynolds", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Ryan%20Reynolds?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 10859, name: "Ryan Gosling", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Ryan%20Gosling?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 1158, name: "Al Pacino", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Al%20Pacino?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 287, name: "Brad Pitt", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Brad%20Pitt?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 139, name: "Quentin Tarantino", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20director%20Quentin%20Tarantino?width=200&height=300&nologo=true", known_for_department: "Directing" },
  { id: 976, name: "Jason Statham", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Jason%20Statham?width=200&height=300&nologo=true", known_for_department: "Acting" },
  { id: 2231, name: "Samuel L. Jackson", profile_path: "https://image.pollinations.ai/prompt/portrait%20photography%20of%20actor%20Samuel%20L.%20Jackson?width=200&height=300&nologo=true", known_for_department: "Acting" }
];

export const MOCK_GENRES = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 18, name: "Drama" },
  { id: 27, name: "Horror" },
  { id: 14, name: "Fantasy" },
  { id: 878, name: "Science Fiction" },
  { id: 53, name: "Thriller" },
  { id: 10749, name: "Romance" },
  { id: 9648, name: "Mystery" },
];
